### PR TITLE
Feat/automated release notes

### PR DESCRIPTION
**Pull request by marcelovicentegc**
#### What is the purpose of this pull request?

To partially automate (one step towards fully automating it) release notes generation based on merged PR labels:

- `🚨 breaking change`
- `🐛 bug`
- `🆕 feature`

The `release.yml` file structures our release notes generated by Github.

image

#### What problem is this solving?

We have to manually type the release notes nowadays. This could be done in a different manner.

#### How should this be manually tested?

You can visit the test repo I created in order to test this feature, and take a look at the generated release notes: https://github.com/marcelovicentegc/release-notes-test/releases.

Also, visit and read Github's documentation on this: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Quality improvement (tests or refactors)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Trivial change (small fix or feature that doesn't impact functionalities)
- [ ] Requires change to documentation, which has been updated accordingly

### CODE REVIEW

**Comment by lucasaarcoverde** [comment]
there is a way of getting the pr description and adding it to the release instead of only the pr title?

**Comment by marcelovicentegc** [comment]
> there is a way of getting the pr description and adding it to the release instead of only the pr title?

It looks like it doesn't, according to the config params: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

But it occurs to me that it's even good for keeping it clean. If someone wants to dig deep into the changes, all they must do is click on the PR link right next to the title. I think that would be enough. Let me know!

**Review by matheusps — COMMENTED** [review]
How dos it work?

**Review by matheusps — APPROVED** [review]

**Review by Lenderson — APPROVED** [review]

**Comment by lucasaarcoverde** [comment]
> > there is a way of getting the pr description and adding it to the release instead of only the pr title?
> 
> It looks like it doesn't, according to the config params: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
> 
> But it occurs to me that it's even good for keeping it clean. If someone wants to dig deep into the changes, all they must do is click on the PR link right next to the title. I think that would be enough. Let me know!

Nice, I didn't see the PR link. I think it would be good to test with a dev branch, to simulate our current process. 
1. Merge PRs with labels (Breaking Change, bug, feature) into the dev branch
2. Merge the dev branch into the main
3. Check what happens
Just pointing this out because I don't know if you covered this case

**Comment by marcelovicentegc** [comment]
> > > there is a way of getting the pr description and adding it to the release instead of only the pr title?
> > 
> > 
> > It looks like it doesn't, according to the config params: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
> > But it occurs to me that it's even good for keeping it clean. If someone wants to dig deep into the changes, all they must do is click on the PR link right next to the title. I think that would be enough. Let me know!
> 
> Nice, I didn't see the PR link. I think it would be good to test with a dev branch, to simulate our current process.
> 
> 1. Merge PRs with labels (Breaking Change, bug, feature) into the dev branch
> 2. Merge the dev branch into the main
> 3. Check what happens
> 
> Just pointing this out because I don't know if you covered this case

I'm good with it! Are we going to make new releases on the `dev` branch? If yes, I think it makes sense! Otherwise, I would go ahead and push this to `main` instead. Let me know @lucasaarcoverde !

**Pull request merged**
